version: '3.1'

services: 
  python:
    build: .
    container_name: hue-control-api
    ports:
      - '8081:8080'
    networks:
      - hue-control-network

networks:
  hue-control-network:
    driver: bridge